spring.application.name=cosaspendientes

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.xqnhdmtlwrckcajzelzs
spring.datasource.password=fbwliaubgrnkng37549743
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
